[workspace]
resolver = "2"
members = [
  "app", 
  "core",
  "core/src/common",
  "core/src/input",
  "core/src/ball",
  "core/src/paddle",
  "core/src/wall",
  "core/src/game_ui",
  "core/src/game_orchestrator",
]

[workspace.dependencies]
bevy = {version = "0.19.0", features = ["debug"]}
bevy_input = {version = "0.19.0"}
bevy_enhanced_input = {version = "0.26.0"}
avian2d = {version = "0.7.0"}

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
