[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
common = { path = "src/common" }
input = { path = "src/input" }
ball = { path = "src/ball" }
paddle = { path = "src/paddle" }
wall = { path = "src/wall" }
game_ui = { path = "src/game_ui" }
game_orchestrator = { path = "src/game_orchestrator" }
level_generator = { path = "src/level_generator" }
