[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
common = { path = "common" }
input = { path = "input" }
ball = { path = "ball" }
paddle = { path = "paddle" }
wall = { path = "wall" }
game_ui = { path = "game_ui" }
game_orchestrator = { path = "game_orchestrator" }
